content:guide:
    - changed-files:
          - any-glob-to-any-file:
                - documentation/guide/**

content:packages:
    - changed-files:
          - any-glob-to-any-file:
                - documentation/packages/**

content:api:
    - changed-files:
          - any-glob-to-any-file:
                - documentation/api/**

content:reference:
    - changed-files:
          - any-glob-to-any-file:
                - documentation/changelog/**
                - documentation/errors/**

config:
    - changed-files:
          - any-glob-to-any-file:
                - docs.json
                - index.mdx
                - style.css
                - logo/**
                - favicon.svg

ci:
    - changed-files:
          - any-glob-to-any-file:
                - .github/**
