content:guide:
    - changed-files:
          - any-glob-to-any-file:
                - guide/*
                - guide/**/*

content:packages:
    - changed-files:
          - any-glob-to-any-file:
                - packages/*
                - packages/**/*

theme:
    - changed-files:
          - any-glob-to-any-file:
                - .vitepress/*
                - .vitepress/**/*

ci:
    - changed-files:
          - any-glob-to-any-file:
                - .github/workflows/*
                - scripts/*
