# Top level styles
StylesPath = styles
MinAlertLevel = suggestion
IgnoredScopes = code, tt, img, url, a
SkippedScopes = script, style, pre, figure

# Parse MDX as Markdown to avoid fragility with JSX
[formats]
mdx = md

# Only match MDX
[*.mdx]
BasedOnStyles = Vale
Vale.Terms = NO

# Ignore JSX/MDX-specific syntax patterns
TokenIgnores = (?sm)((?:import|export) .+?$), \
(?<!`)(<\w+ ?.+ ?\/>)(?!`), \
(<[A-Z]\w+>.+?<\/[A-Z]\w+>), \
\{[^}]*\}

# Exclude multiline JSX and curly braces
BlockIgnores = (?sm)^(<\w+\n .*\s\/>)$, \
(?sm)^({.+.*})
