name: ci

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    merge_group:
        branches:
            - main

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

jobs:
    lint:
        name: 🔠 Lint project
        runs-on: ubuntu-24.04-arm
        timeout-minutes: 15

        steps:
            - name: Checkout Project
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false

            - name: Setup pnpm + Node.js v24
              uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
              with:
                  runtime: node@24
                  cache: true
                  install: false

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Run lint
              run: pnpm lint
