name: Semantic Pull Requests

on:
    # zizmor: ignore[dangerous-triggers]
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions: {}

jobs:
    semantic-pr:
        name: Validate PR title
        runs-on: blacksmith-4vcpu-ubuntu-2404
        if: github.repository == 'wolfstar-project/website'
        permissions:
            contents: read
            pull-requests: read
            statuses: write
        steps:
            - name: Validate PR title
              uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
              with:
                  types: |
                      feat
                      fix
                      docs
                      style
                      refactor
                      perf
                      build
                      ci
                      chore
                      revert
                  scopes: |
                      guide
                      packages
                      theme
                      api
                      deps
                      ci
                  subjectPattern: ^(?![A-Z]).+$
                  subjectPatternError: |
                      The subject "{subject}" found in the pull request title "{title}"
                      did not match the configured pattern. Please ensure that the subject
                      does not start with an uppercase character.
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
